#cloud-config
hostname: <hostname>
user: <user>
password: <password>
chpasswd: { expire: false }
ssh_pwauth: true
lock_passwd: false

package_upgrade: true
packages:
  - git
  - curl

runcmd:
  # 1) Clone git repo
  - git clone https://github.com/mattermost/docker /opt/mattermost
  - cd /opt/mattermost

  # 2) Setup mattermost env
  - cp env.example .env
  - sed -i "s/DOMAIN=mm.example.com/DOMAIN=<domain>/" .env
  - echo "MM_SERVICESETTINGS_ALLOWCORSFROM=*\nMM_SERVICESETTINGS_WEBSOCKETURL=wss://${DOMAIN}" >> .env

  # 3) Setup directories and permissions
  # Use /bin/bash, as dash (default on Debian) does not support the below mkdir syntax
  - /bin/bash -c "mkdir -p ./volumes/app/mattermost/{config,data,logs,plugins,client/plugins,bleve-indexes}"
  - chown -R 2000:2000 ./volumes/app/mattermost

  # 4) Start mattermost
  - docker compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d
